In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Wczytanie pliku CSV

In [15]:
df = pd.read_csv('data/iris.csv')
pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')

print(df['sepal_length'].dtype)
print(df['species'].dtype)

df2 = pd.read_csv('data/LaqnData.csv')
print(df2['ReadingDateTime'].dtype.name)
df2

float64
object
object

       Site Species   ReadingDateTime   Value Units Provisional or Ratified
0       BG1      BP  01/01/2017 00:00     NaN  mBar                       P
1       BG1      BP  01/01/2017 00:15  1018.0  mBar                       P
2       BG1      BP  01/01/2017 00:30  1018.0  mBar                       P
3       BG1      BP  01/01/2017 00:45  1017.0  mBar                       P
4       BG1      BP  01/01/2017 01:00  1017.0  mBar                       P
5       BG1      BP  01/01/2017 01:15  1017.0  mBar                       P
6       BG1      BP  01/01/2017 01:30  1017.0  mBar                       P
7       BG1      BP  01/01/2017 01:45  1017.0  mBar                       P
8       BG1      BP  01/01/2017 02:00  1016.0  mBar                       P
9       BG1      BP  01/01/2017 02:15  1016.0  mBar                       P
10      BG1      BP  01/01/2017 02:30  1016.0  mBar                       P
11      BG1      BP  01/01/2017 02:45  1015.0  mBar                       P
12      BG1      BP  01/01/2017 03:00  1015.0  mBar                       P
13      BG1      BP  01/01/2017 03:15  1015.0  mBar                       P
14      BG1      BP  01/01/2017 03:30  1015.0  mBar                       P
15      BG1      BP  01/01/2017 03:45  1014.0  mBar                       P
16      BG1      BP  01/01/2017 04:00  1014.0  mBar                       P
17      BG1      BP  01/01/2017 04:15  1014.0  mBar                       P
18      BG1      BP  01/01/2017 04:30  1014.0  mBar                       P
19      BG1      BP  01/01/2017 04:45  1013.0  mBar                       P
20      BG1      BP  01/01/2017 05:00  1013.0  mBar                       P
21      BG1      BP  01/01/2017 05:15  1013.0  mBar                       P
22      BG1      BP  01/01/2017 05:30  1013.0  mBar                       P
23      BG1      BP  01/01/2017 05:45  1012.0  mBar                       P
24      BG1      BP  01/01/2017 06:00  1012.0  mBar                       P
25      BG1      BP  01/01/2017 06:15  1012.0  mBar                       P
26      BG1      BP  01/01/2017 06:30  1012.0  mBar                       P
27      BG1      BP  01/01/2017 06:45  1012.0  mBar                       P
28      BG1      BP  01/01/2017 07:00  1012.0  mBar                       P
29      BG1      BP  01/01/2017 07:15  1012.0  mBar                       P
...     ...     ...               ...     ...   ...                     ...
175170  BG1    WSPD  31/12/2017 16:30     NaN   m/s                       P
175171  BG1    WSPD  31/12/2017 16:45     NaN   m/s                       P
175172  BG1    WSPD  31/12/2017 17:00     NaN   m/s                       P
175173  BG1    WSPD  31/12/2017 17:15     NaN   m/s                       P
175174  BG1    WSPD  31/12/2017 17:30     NaN   m/s                       P
175175  BG1    WSPD  31/12/2017 17:45     NaN   m/s                       P
175176  BG1    WSPD  31/12/2017 18:00     NaN   m/s                       P
175177  BG1    WSPD  31/12/2017 18:15     NaN   m/s                       P
175178  BG1    WSPD  31/12/2017 18:30     NaN   m/s                       P
175179  BG1    WSPD  31/12/2017 18:45     NaN   m/s                       P
175180  BG1    WSPD  31/12/2017 19:00     NaN   m/s                       P
175181  BG1    WSPD  31/12/2017 19:15     NaN   m/s                       P
175182  BG1    WSPD  31/12/2017 19:30     NaN   m/s                       P
175183  BG1    WSPD  31/12/2017 19:45     NaN   m/s                       P
175184  BG1    WSPD  31/12/2017 20:00     NaN   m/s                       P
175185  BG1    WSPD  31/12/2017 20:15     NaN   m/s                       P
175186  BG1    WSPD  31/12/2017 20:30     NaN   m/s                       P
175187  BG1    WSPD  31/12/2017 20:45     NaN   m/s                       P
175188  BG1    WSPD  31/12/2017 21:00     NaN   m/s                       P
175189  BG1    WSPD  31/12/2017 21:15     NaN   m/s                       P
175190  BG1    WSPD  31/12/2017 21:30     NaN   m/s                       P
175191  BG1    WSPD  31/12/2017 21:45     NaN   m/s                       P
175192  BG1    WSPD  31/12/2017 22:00     NaN   m/s                       P
175193  BG1    WSPD  31/12/2017 22:15     NaN   m/s                       P
175194  BG1    WSPD  31/12/2017 22:30     NaN   m/s                       P
175195  BG1    WSPD  31/12/2017 22:45     NaN   m/s                       P
175196  BG1    WSPD  31/12/2017 23:00     NaN   m/s                       P
175197  BG1    WSPD  31/12/2017 23:15     NaN   m/s                       P
175198  BG1    WSPD  31/12/2017 23:30     NaN   m/s                       P
175199  BG1    WSPD  31/12/2017 23:45     NaN   m/s                       P

[175200 rows x 6 columns]

In [ ]:
from io import StringIO

csv_data = """
sepal_length,sepal_width,petal_length,petal_width,species
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
4.7,3.2,1.3,0.2,setosa
4.6,3.1,1.5,0.2,setosa
5,3.6,1.4,0.2,setosa
5.4,3.9,1.7,0.4,setosa
4.6,3.4,1.4,0.3,setosa
5,3.4,1.5,0.2,setosa
7,3.2,4.7,1.4,versicolor
6.4,3.2,4.5,1.5,versicolor
6.9,3.1,4.9,1.5,versicolor
5.5,2.3,4,1.3,versicolor
6.5,2.8,4.6,1.5,versicolor
5.7,2.8,4.5,1.3,versicolor
6.3,3.3,4.7,1.6,versicolor
4.9,2.4,3.3,1,versicolor
6.3,3.3,6,2.5,virginica
5.8,2.7,5.1,1.9,virginica
7.1,3,5.9,2.1,virginica
6.3,2.9,5.6,1.8,virginica
6.5,3,5.8,2.2,virginica
7.6,3,6.6,2.1,virginica
4.9,2.5,4.5,1.7,virginica
7.3,2.9,6.3,1.8,virginica
6.7,2.5,5.8,1.8,virginica
"""

In [ ]:
missing_values = """
sepal_length,sepal_width,petal_length,petal_width,species
5.1,,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
4.7,3.2,1.3,0.2,setosa
4.6,3.1,,0.2,setosa
5,3.6,1.4,0.2,setosa
5.4,3.9,1.7,0.4,setosa
,3.4,1.4,0.3,setosa
,3.4,1.5,0.2,setosa
7,3.2,4.7,,versicolor
6.4,3.2,4.5,1.5,versicolor
6.9,3.1,4.9,1.5,versicolor
5.5,2.3,4,1.3,versicolor
6.5,,,1.5,versicolor
5.7,2.8,4.5,1.3,versicolor
6.3,,4.7,1.6,versicolor
4.9,2.4,,1,versicolor
6.3,3.3,,2.5,virginica
5.8,2.7,5.1,1.9,virginica
7.1,3,5.9,2.1,virginica
6.3,,5.6,1.8,virginica
6.5,3,,2.2,virginica
7.6,3,6.6,2.1,virginica
4.9,,4.5,1.7,virginica
,2.9,6.3,,virginica
6.7,,5.8,1.8,virginica
"""

In [ ]:
# csv_data: str
csv_strio = StringIO(missing_values)
df = pd.read_csv(csv_strio)
df

In [ ]:
df.fillna(0)

In [ ]:
df.fillna(0, inplace=True)
df

In [ ]:
df2 = pd.DataFrame([[1,2,3], [4, 5, 6], [7, 8, 9], [0, np.NaN, 0], [0, 0, np.NaN]], columns=list('ABC'))

In [ ]:
df2 = pd.DataFrame([[1,2,3], [4, 5, 6], [7, 8, 9], [0, np.NaN, 0], [0, 0, np.NaN]], columns=list('ABC'))
print(df2.mean())
df2.fillna(df2.mean())
df2.fillna?

In [ ]:
df = pd.DataFrame([[1, 'abc;def;ghi'],[2, 'jkl;mno'], [3, 'pqr;stu;vwx']], columns=list('AB'))
print(df)
split_B = df.B.str.split(';', expand=True).rename(columns=lambda x: f'B_{x}')
df.join(split_B)

# Grupowanie i agregacja

In [ ]:
nycflights13_csv = """
"year","month","day","dep_time","dep_delay","arr_time","arr_delay","carrier","tailnum","flight","origin","dest","air_time","distance","hour","minute"
2013,1,1,517,2,830,11,"UA","N14228",1545,"EWR","IAH",227,1400,5,17
2013,1,1,533,4,850,20,"UA","N24211",1714,"LGA","IAH",227,1416,5,33
2013,1,1,542,2,923,33,"AA","N619AA",1141,"JFK","MIA",160,1089,5,42
2013,1,1,544,-1,1004,-18,"B6","N804JB",725,"JFK","BQN",183,1576,5,44
2013,1,1,554,-6,812,-25,"DL","N668DN",461,"LGA","ATL",116,762,5,54
2013,1,1,554,-4,740,12,"UA","N39463",1696,"EWR","ORD",150,719,5,54
2013,1,5,555,-5,913,19,"B6","N516JB",507,"EWR","FLL",158,1065,5,55
2013,1,5,557,-3,709,-14,"EV","N829AS",5708,"LGA","IAD",53,229,5,57
2013,1,5,557,-3,838,-8,"B6","N593JB",79,"JFK","MCO",140,944,5,57
2013,1,1,558,-2,753,8,"AA","N3ALAA",301,"LGA","ORD",138,733,5,58
2013,1,1,558,-2,849,-2,"B6","N793JB",49,"JFK","PBI",149,1028,5,58
2013,1,1,558,-2,853,-3,"B6","N657JB",71,"JFK","TPA",158,1005,5,58
2013,1,1,558,-2,924,7,"UA","N29129",194,"JFK","LAX",345,2475,5,58
2013,3,1,454,-6,633,-15,"US","N177US",1117,"EWR","CLT",79,529,4,54
2013,3,1,505,-10,746,-24,"UA","N527UA",475,"EWR","IAH",199,1400,5,5
2013,3,1,521,-9,813,-14,"UA","N76523",1714,"LGA","IAH",213,1416,5,21
2013,3,1,537,-3,856,6,"AA","N5EPAA",1141,"JFK","MIA",173,1089,5,37
2013,3,1,541,-4,1014,-9,"B6","N653JB",725,"JFK","BQN",191,1576,5,41
2013,3,1,549,-11,639,-24,"US","N749US",2114,"LGA","BOS",31,184,5,49
2013,3,1,550,-10,747,-14,"EV","N760EV",4911,"EWR","DTW",89,488,5,50
2013,3,4,551,-8,722,-1,"EV","N26549",4608,"EWR","MKE",119,725,5,51
2013,3,4,551,-9,717,-28,"AA","N3DCAA",301,"LGA","ORD",113,733,5,51
2013,3,4,551,-9,845,-16,"B6","N566JB",371,"LGA","FLL",155,1076,5,51
2013,3,4,552,-8,656,-39,"MQ","N520MQ",3768,"EWR","ORD",108,719,5,52
2013,5,1,9,434,308,408,"VX","N628VA",413,"JFK","LAX",341,2475,0,9
2013,5,1,451,-9,641,1,"US","N196UW",1219,"EWR","CLT",94,529,4,51
2013,5,1,537,-3,836,-4,"AA","N5BYAA",701,"JFK","MIA",144,1089,5,37
2013,5,1,544,-1,818,-9,"UA","N494UA",450,"LGA","IAH",190,1416,5,44
2013,5,1,548,-12,831,-23,"B6","N523JB",371,"LGA","FLL",140,1076,5,48
2013,5,1,549,-11,804,-6,"MQ","N520MQ",4650,"LGA","ATL",113,762,5,49
2013,5,1,553,-7,700,-12,"EV","N877AS",5747,"LGA","IAD",48,229,5,53
2013,5,2,553,-7,655,-6,"US","N702UW",2114,"LGA","BOS",35,184,5,53
2013,5,2,554,-6,731,-25,"DL","N327NB",731,"LGA","DTW",74,502,5,54
2013,5,2,554,-6,707,-18,"UA","N439UA",635,"LGA","ORD",112,733,5,54

"""

In [ ]:
nycflights13 = StringIO(nycflights13_csv)
df13 = pd.read_csv(nycflights13)
df13.sample(5)

In [ ]:
df13.groupby('month').median()

In [ ]:
df13.groupby(['month', 'day']).mean()

In [ ]:
df13.groupby('month', as_index=False).aggregate({"distance": "sum"})

In [ ]:
aggregations = {
    'arr_time': [min, max, sum],        
    'arr_delay': 'mean',            
    'day': ['first', 'nunique']
}

df13.groupby('month').agg(aggregations)

In [ ]:
df13['air_time'].groupby(df13['month']).apply(np.sum)